<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Scission du hadith (phase 3) : `hadith_cluster` porte l'enseignement,
 * `riwaya` porte le texte, la citation et la chaîne.
 *
 * Migration PostgreSQL : dev et test tournent sur SQLite.
 */
final class Version20260727223622 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Scission du hadith en enseignement (cluster) et occurrences (riwāyāt)';
    }

    private function abortUnlessPostgres(): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration PostgreSQL uniquement. En dev/test la base est SQLite : utiliser `make db-sync`.',
        );
    }

    /**
     * Les anciennes tables sont supprimées, pas transformées : Postgres ne
     * porte que le schéma, le corpus vient de `IsnadDatasetLoader`. Si des
     * lignes existent, elles ont été saisies ailleurs et la migration s'arrête
     * plutôt que de les détruire.
     */
    private function abortIfHadithDataExists(): void
    {
        $rows = (int) $this->connection->fetchOne('SELECT COUNT(*) FROM hadith');

        $this->abortIf(
            $rows > 0,
            \sprintf('La table « hadith » contient %d ligne(s) : exporter le corpus avant de rejouer la scission.', $rows),
        );
    }

    public function up(Schema $schema): void
    {
        $this->abortUnlessPostgres();
        $this->abortIfHadithDataExists();

        $this->addSql('CREATE TABLE hadith_cluster (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(64) NOT NULL, label VARCHAR(255) NOT NULL, theme VARCHAR(255) DEFAULT NULL, intro TEXT DEFAULT NULL, turuq VARCHAR(64) DEFAULT NULL, ready BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_51214517989D9B62 ON hadith_cluster (slug)');
        $this->addSql('CREATE INDEX IDX_51214517B03A8386 ON hadith_cluster (created_by_id)');
        $this->addSql('CREATE INDEX IDX_51214517896DBBDE ON hadith_cluster (updated_by_id)');
        $this->addSql('CREATE TABLE riwaya (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(64) NOT NULL, text_fr TEXT NOT NULL, text_ar TEXT DEFAULT NULL, reference VARCHAR(255) NOT NULL, grade VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, cluster_id INT NOT NULL, pivot_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_18BFB216989D9B62 ON riwaya (slug)');
        $this->addSql('CREATE INDEX IDX_18BFB216C36A3328 ON riwaya (cluster_id)');
        $this->addSql('CREATE INDEX IDX_18BFB2166C186266 ON riwaya (pivot_id)');
        $this->addSql('CREATE INDEX IDX_18BFB216B03A8386 ON riwaya (created_by_id)');
        $this->addSql('CREATE INDEX IDX_18BFB216896DBBDE ON riwaya (updated_by_id)');
        $this->addSql('CREATE TABLE riwaya_person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, chains VARCHAR(32) DEFAULT NULL, bio TEXT DEFAULT NULL, work VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, riwaya_id INT NOT NULL, person_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_99D9CDCAF3C778CD ON riwaya_person (riwaya_id)');
        $this->addSql('CREATE INDEX IDX_99D9CDCA217BBB47 ON riwaya_person (person_id)');
        $this->addSql('CREATE INDEX IDX_99D9CDCAB03A8386 ON riwaya_person (created_by_id)');
        $this->addSql('CREATE INDEX IDX_99D9CDCA896DBBDE ON riwaya_person (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_riwaya_person ON riwaya_person (riwaya_id, person_id)');
        $this->addSql('CREATE TABLE riwaya_reference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(32) DEFAULT NULL, is_primary BOOLEAN NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, riwaya_id INT NOT NULL, collection_id INT NOT NULL, edition_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F4FAE718F3C778CD ON riwaya_reference (riwaya_id)');
        $this->addSql('CREATE INDEX IDX_F4FAE718514956FD ON riwaya_reference (collection_id)');
        $this->addSql('CREATE INDEX IDX_F4FAE71874281A5E ON riwaya_reference (edition_id)');
        $this->addSql('CREATE INDEX IDX_F4FAE718B03A8386 ON riwaya_reference (created_by_id)');
        $this->addSql('CREATE INDEX IDX_F4FAE718896DBBDE ON riwaya_reference (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_riwaya_reference ON riwaya_reference (riwaya_id, collection_id, number)');
        $this->addSql('ALTER TABLE hadith_cluster ADD CONSTRAINT FK_51214517B03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hadith_cluster ADD CONSTRAINT FK_51214517896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya ADD CONSTRAINT FK_18BFB216C36A3328 FOREIGN KEY (cluster_id) REFERENCES hadith_cluster (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya ADD CONSTRAINT FK_18BFB2166C186266 FOREIGN KEY (pivot_id) REFERENCES person (id)');
        $this->addSql('ALTER TABLE riwaya ADD CONSTRAINT FK_18BFB216B03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya ADD CONSTRAINT FK_18BFB216896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya_person ADD CONSTRAINT FK_99D9CDCAF3C778CD FOREIGN KEY (riwaya_id) REFERENCES riwaya (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya_person ADD CONSTRAINT FK_99D9CDCA217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya_person ADD CONSTRAINT FK_99D9CDCAB03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya_person ADD CONSTRAINT FK_99D9CDCA896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya_reference ADD CONSTRAINT FK_F4FAE718F3C778CD FOREIGN KEY (riwaya_id) REFERENCES riwaya (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya_reference ADD CONSTRAINT FK_F4FAE718514956FD FOREIGN KEY (collection_id) REFERENCES collection (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya_reference ADD CONSTRAINT FK_F4FAE71874281A5E FOREIGN KEY (edition_id) REFERENCES edition (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya_reference ADD CONSTRAINT FK_F4FAE718B03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE riwaya_reference ADD CONSTRAINT FK_F4FAE718896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hadith DROP CONSTRAINT fk_a4fb70a6c186266');
        $this->addSql('ALTER TABLE hadith DROP CONSTRAINT fk_a4fb70ab03a8386');
        $this->addSql('ALTER TABLE hadith DROP CONSTRAINT fk_a4fb70a896dbbde');
        $this->addSql('ALTER TABLE hadith_person DROP CONSTRAINT fk_db4e658ab03a8386');
        $this->addSql('ALTER TABLE hadith_person DROP CONSTRAINT fk_db4e658a896dbbde');
        $this->addSql('ALTER TABLE hadith_person DROP CONSTRAINT fk_db4e658a26312492');
        $this->addSql('ALTER TABLE hadith_person DROP CONSTRAINT fk_db4e658a217bbb47');
        $this->addSql('ALTER TABLE hadith_reference DROP CONSTRAINT fk_8cd55a9c896dbbde');
        $this->addSql('ALTER TABLE hadith_reference DROP CONSTRAINT fk_8cd55a9c26312492');
        $this->addSql('ALTER TABLE hadith_reference DROP CONSTRAINT fk_8cd55a9c514956fd');
        $this->addSql('ALTER TABLE hadith_reference DROP CONSTRAINT fk_8cd55a9c74281a5e');
        $this->addSql('ALTER TABLE hadith_reference DROP CONSTRAINT fk_8cd55a9cb03a8386');
        $this->addSql('ALTER TABLE transmission DROP CONSTRAINT fk_7f87199f26312492');
        $this->addSql('DROP TABLE hadith');
        $this->addSql('DROP TABLE hadith_person');
        $this->addSql('DROP TABLE hadith_reference');
        $this->addSql('DROP INDEX uniq_transmission');
        $this->addSql('DROP INDEX idx_7f87199f26312492');
        $this->addSql('ALTER TABLE transmission RENAME COLUMN hadith_id TO riwaya_id');
        $this->addSql('ALTER TABLE transmission ADD CONSTRAINT FK_7F87199FF3C778CD FOREIGN KEY (riwaya_id) REFERENCES riwaya (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_7F87199FF3C778CD ON transmission (riwaya_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_transmission ON transmission (riwaya_id, from_person_id, to_person_id)');
    }

    public function down(Schema $schema): void
    {
        $this->abortUnlessPostgres();

        $this->addSql('CREATE TABLE hadith (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(64) NOT NULL, label VARCHAR(255) NOT NULL, text_fr TEXT NOT NULL, text_ar TEXT DEFAULT NULL, reference VARCHAR(255) NOT NULL, grade VARCHAR(64) DEFAULT NULL, theme VARCHAR(255) DEFAULT NULL, intro TEXT DEFAULT NULL, turuq VARCHAR(64) DEFAULT NULL, ready BOOLEAN NOT NULL, pivot_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_a4fb70a989d9b62 ON hadith (slug)');
        $this->addSql('CREATE INDEX idx_a4fb70a896dbbde ON hadith (updated_by_id)');
        $this->addSql('CREATE INDEX idx_a4fb70a6c186266 ON hadith (pivot_id)');
        $this->addSql('CREATE INDEX idx_a4fb70ab03a8386 ON hadith (created_by_id)');
        $this->addSql('CREATE TABLE hadith_person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, chains VARCHAR(32) DEFAULT NULL, bio TEXT DEFAULT NULL, work VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, hadith_id INT NOT NULL, person_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_hadith_person ON hadith_person (hadith_id, person_id)');
        $this->addSql('CREATE INDEX idx_db4e658a26312492 ON hadith_person (hadith_id)');
        $this->addSql('CREATE INDEX idx_db4e658ab03a8386 ON hadith_person (created_by_id)');
        $this->addSql('CREATE INDEX idx_db4e658a896dbbde ON hadith_person (updated_by_id)');
        $this->addSql('CREATE INDEX idx_db4e658a217bbb47 ON hadith_person (person_id)');
        $this->addSql('CREATE TABLE hadith_reference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(32) DEFAULT NULL, is_primary BOOLEAN NOT NULL, "position" INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, hadith_id INT NOT NULL, collection_id INT NOT NULL, edition_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_hadith_reference ON hadith_reference (hadith_id, collection_id, number)');
        $this->addSql('CREATE INDEX idx_8cd55a9c26312492 ON hadith_reference (hadith_id)');
        $this->addSql('CREATE INDEX idx_8cd55a9c514956fd ON hadith_reference (collection_id)');
        $this->addSql('CREATE INDEX idx_8cd55a9c74281a5e ON hadith_reference (edition_id)');
        $this->addSql('CREATE INDEX idx_8cd55a9cb03a8386 ON hadith_reference (created_by_id)');
        $this->addSql('CREATE INDEX idx_8cd55a9c896dbbde ON hadith_reference (updated_by_id)');
        $this->addSql('ALTER TABLE hadith ADD CONSTRAINT fk_a4fb70a6c186266 FOREIGN KEY (pivot_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith ADD CONSTRAINT fk_a4fb70ab03a8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith ADD CONSTRAINT fk_a4fb70a896dbbde FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith_person ADD CONSTRAINT fk_db4e658ab03a8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith_person ADD CONSTRAINT fk_db4e658a896dbbde FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith_person ADD CONSTRAINT fk_db4e658a26312492 FOREIGN KEY (hadith_id) REFERENCES hadith (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith_person ADD CONSTRAINT fk_db4e658a217bbb47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith_reference ADD CONSTRAINT fk_8cd55a9c896dbbde FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith_reference ADD CONSTRAINT fk_8cd55a9c26312492 FOREIGN KEY (hadith_id) REFERENCES hadith (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith_reference ADD CONSTRAINT fk_8cd55a9c514956fd FOREIGN KEY (collection_id) REFERENCES collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith_reference ADD CONSTRAINT fk_8cd55a9c74281a5e FOREIGN KEY (edition_id) REFERENCES edition (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith_reference ADD CONSTRAINT fk_8cd55a9cb03a8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hadith_cluster DROP CONSTRAINT FK_51214517B03A8386');
        $this->addSql('ALTER TABLE hadith_cluster DROP CONSTRAINT FK_51214517896DBBDE');
        $this->addSql('ALTER TABLE riwaya DROP CONSTRAINT FK_18BFB216C36A3328');
        $this->addSql('ALTER TABLE riwaya DROP CONSTRAINT FK_18BFB2166C186266');
        $this->addSql('ALTER TABLE riwaya DROP CONSTRAINT FK_18BFB216B03A8386');
        $this->addSql('ALTER TABLE riwaya DROP CONSTRAINT FK_18BFB216896DBBDE');
        $this->addSql('ALTER TABLE riwaya_person DROP CONSTRAINT FK_99D9CDCAF3C778CD');
        $this->addSql('ALTER TABLE riwaya_person DROP CONSTRAINT FK_99D9CDCA217BBB47');
        $this->addSql('ALTER TABLE riwaya_person DROP CONSTRAINT FK_99D9CDCAB03A8386');
        $this->addSql('ALTER TABLE riwaya_person DROP CONSTRAINT FK_99D9CDCA896DBBDE');
        $this->addSql('ALTER TABLE riwaya_reference DROP CONSTRAINT FK_F4FAE718F3C778CD');
        $this->addSql('ALTER TABLE riwaya_reference DROP CONSTRAINT FK_F4FAE718514956FD');
        $this->addSql('ALTER TABLE riwaya_reference DROP CONSTRAINT FK_F4FAE71874281A5E');
        $this->addSql('ALTER TABLE riwaya_reference DROP CONSTRAINT FK_F4FAE718B03A8386');
        $this->addSql('ALTER TABLE riwaya_reference DROP CONSTRAINT FK_F4FAE718896DBBDE');
        $this->addSql('ALTER TABLE transmission DROP CONSTRAINT FK_7F87199FF3C778CD');
        $this->addSql('DROP TABLE hadith_cluster');
        $this->addSql('DROP TABLE riwaya');
        $this->addSql('DROP TABLE riwaya_person');
        $this->addSql('DROP TABLE riwaya_reference');
        $this->addSql('DROP INDEX IDX_7F87199FF3C778CD');
        $this->addSql('DROP INDEX uniq_transmission');
        $this->addSql('ALTER TABLE transmission RENAME COLUMN riwaya_id TO hadith_id');
        $this->addSql('ALTER TABLE transmission ADD CONSTRAINT fk_7f87199f26312492 FOREIGN KEY (hadith_id) REFERENCES hadith (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_7f87199f26312492 ON transmission (hadith_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_transmission ON transmission (hadith_id, from_person_id, to_person_id)');
    }
}
