<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Schéma initial, en SQL PostgreSQL (plateforme de prod).
 *
 * Les env dev et test tournent sur SQLite (config/packages/{dev,test}/doctrine.yaml)
 * et construisent leur schéma depuis les entités, pas depuis les migrations.
 */
final class Version20260726173631 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial : period, person, hadith, hadith_person, transmission';
    }

    /**
     * Empêche l'exécution hors PostgreSQL : sans ce garde, un `bin/console d:m:m`
     * lancé en dev attaque SQLite et échoue en plein milieu du DDL.
     */
    private function abortUnlessPostgres(): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration PostgreSQL uniquement. En dev/test la base est SQLite : utiliser `make db-sync`, ou `make migrate` pour viser le conteneur Postgres.',
        );
    }

    public function up(Schema $schema): void
    {
        $this->abortUnlessPostgres();

        $this->addSql('CREATE TABLE hadith (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(64) NOT NULL, label VARCHAR(255) NOT NULL, text_fr TEXT NOT NULL, text_ar TEXT DEFAULT NULL, reference VARCHAR(255) NOT NULL, grade VARCHAR(64) DEFAULT NULL, theme VARCHAR(255) DEFAULT NULL, intro TEXT DEFAULT NULL, turuq VARCHAR(64) DEFAULT NULL, ready BOOLEAN NOT NULL, pivot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4FB70A989D9B62 ON hadith (slug)');
        $this->addSql('CREATE INDEX IDX_A4FB70A6C186266 ON hadith (pivot_id)');
        $this->addSql('CREATE TABLE hadith_person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, chains VARCHAR(32) DEFAULT NULL, bio TEXT DEFAULT NULL, work VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, hadith_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB4E658A26312492 ON hadith_person (hadith_id)');
        $this->addSql('CREATE INDEX IDX_DB4E658A217BBB47 ON hadith_person (person_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_hadith_person ON hadith_person (hadith_id, person_id)');
        $this->addSql('CREATE TABLE period (id VARCHAR(32) NOT NULL, label_fr VARCHAR(64) NOT NULL, label_ar VARCHAR(64) NOT NULL, color VARCHAR(7) NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, name_ar VARCHAR(255) DEFAULT NULL, meta VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, role VARCHAR(255) DEFAULT NULL, bio TEXT DEFAULT NULL, work VARCHAR(255) DEFAULT NULL, period_id VARCHAR(32) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34DCD176989D9B62 ON person (slug)');
        $this->addSql('CREATE INDEX IDX_34DCD176EC8B7ADE ON person (period_id)');
        $this->addSql('CREATE TABLE transmission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, spine BOOLEAN NOT NULL, hadith_id INT NOT NULL, from_person_id INT NOT NULL, to_person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7F87199F26312492 ON transmission (hadith_id)');
        $this->addSql('CREATE INDEX idx_transmission_from ON transmission (from_person_id)');
        $this->addSql('CREATE INDEX idx_transmission_to ON transmission (to_person_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_transmission ON transmission (hadith_id, from_person_id, to_person_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE hadith ADD CONSTRAINT FK_A4FB70A6C186266 FOREIGN KEY (pivot_id) REFERENCES person (id)');
        $this->addSql('ALTER TABLE hadith_person ADD CONSTRAINT FK_DB4E658A26312492 FOREIGN KEY (hadith_id) REFERENCES hadith (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hadith_person ADD CONSTRAINT FK_DB4E658A217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176EC8B7ADE FOREIGN KEY (period_id) REFERENCES period (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transmission ADD CONSTRAINT FK_7F87199F26312492 FOREIGN KEY (hadith_id) REFERENCES hadith (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transmission ADD CONSTRAINT FK_7F87199F31E72EFD FOREIGN KEY (from_person_id) REFERENCES person (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transmission ADD CONSTRAINT FK_7F87199F10D86C36 FOREIGN KEY (to_person_id) REFERENCES person (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->abortUnlessPostgres();

        $this->addSql('ALTER TABLE hadith DROP CONSTRAINT FK_A4FB70A6C186266');
        $this->addSql('ALTER TABLE hadith_person DROP CONSTRAINT FK_DB4E658A26312492');
        $this->addSql('ALTER TABLE hadith_person DROP CONSTRAINT FK_DB4E658A217BBB47');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD176EC8B7ADE');
        $this->addSql('ALTER TABLE transmission DROP CONSTRAINT FK_7F87199F26312492');
        $this->addSql('ALTER TABLE transmission DROP CONSTRAINT FK_7F87199F31E72EFD');
        $this->addSql('ALTER TABLE transmission DROP CONSTRAINT FK_7F87199F10D86C36');
        $this->addSql('DROP TABLE hadith');
        $this->addSql('DROP TABLE hadith_person');
        $this->addSql('DROP TABLE period');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE transmission');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
