<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Comptes de curateurs et traçabilité des entités curatées (phase 0).
 *
 * Migration PostgreSQL : les env dev et test tournent sur SQLite et
 * construisent leur schéma depuis les entités.
 */
final class Version20260726202634 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Comptes de curateurs, attribution et verrou optimiste';
    }

    private function abortUnlessPostgres(): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration PostgreSQL uniquement. En dev/test la base est SQLite : utiliser `make db-sync`.',
        );
    }

    public function up(Schema $schema): void
    {
        $this->abortUnlessPostgres();

        $this->addSql('CREATE TABLE curator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, display_name VARCHAR(100) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_curator_email ON curator (email)');
        $this->addSql('ALTER TABLE hadith ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE hadith ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE hadith ADD version INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE hadith ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hadith ADD updated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hadith ADD CONSTRAINT FK_A4FB70AB03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hadith ADD CONSTRAINT FK_A4FB70A896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_A4FB70AB03A8386 ON hadith (created_by_id)');
        $this->addSql('CREATE INDEX IDX_A4FB70A896DBBDE ON hadith (updated_by_id)');
        $this->addSql('ALTER TABLE hadith_person ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE hadith_person ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE hadith_person ADD version INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE hadith_person ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hadith_person ADD updated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE hadith_person ADD CONSTRAINT FK_DB4E658AB03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hadith_person ADD CONSTRAINT FK_DB4E658A896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_DB4E658AB03A8386 ON hadith_person (created_by_id)');
        $this->addSql('CREATE INDEX IDX_DB4E658A896DBBDE ON hadith_person (updated_by_id)');
        $this->addSql('ALTER TABLE person ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD version INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE person ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD updated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176B03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_34DCD176B03A8386 ON person (created_by_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176896DBBDE ON person (updated_by_id)');
        $this->addSql('ALTER TABLE transmission ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE transmission ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE transmission ADD version INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE transmission ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE transmission ADD updated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE transmission ADD CONSTRAINT FK_7F87199FB03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transmission ADD CONSTRAINT FK_7F87199F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_7F87199FB03A8386 ON transmission (created_by_id)');
        $this->addSql('CREATE INDEX IDX_7F87199F896DBBDE ON transmission (updated_by_id)');
    }

    public function down(Schema $schema): void
    {
        $this->abortUnlessPostgres();

        $this->addSql('DROP TABLE curator');
        $this->addSql('ALTER TABLE hadith DROP CONSTRAINT FK_A4FB70AB03A8386');
        $this->addSql('ALTER TABLE hadith DROP CONSTRAINT FK_A4FB70A896DBBDE');
        $this->addSql('DROP INDEX IDX_A4FB70AB03A8386');
        $this->addSql('DROP INDEX IDX_A4FB70A896DBBDE');
        $this->addSql('ALTER TABLE hadith DROP created_at');
        $this->addSql('ALTER TABLE hadith DROP updated_at');
        $this->addSql('ALTER TABLE hadith DROP version');
        $this->addSql('ALTER TABLE hadith DROP created_by_id');
        $this->addSql('ALTER TABLE hadith DROP updated_by_id');
        $this->addSql('ALTER TABLE hadith_person DROP CONSTRAINT FK_DB4E658AB03A8386');
        $this->addSql('ALTER TABLE hadith_person DROP CONSTRAINT FK_DB4E658A896DBBDE');
        $this->addSql('DROP INDEX IDX_DB4E658AB03A8386');
        $this->addSql('DROP INDEX IDX_DB4E658A896DBBDE');
        $this->addSql('ALTER TABLE hadith_person DROP created_at');
        $this->addSql('ALTER TABLE hadith_person DROP updated_at');
        $this->addSql('ALTER TABLE hadith_person DROP version');
        $this->addSql('ALTER TABLE hadith_person DROP created_by_id');
        $this->addSql('ALTER TABLE hadith_person DROP updated_by_id');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD176B03A8386');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD176896DBBDE');
        $this->addSql('DROP INDEX IDX_34DCD176B03A8386');
        $this->addSql('DROP INDEX IDX_34DCD176896DBBDE');
        $this->addSql('ALTER TABLE person DROP created_at');
        $this->addSql('ALTER TABLE person DROP updated_at');
        $this->addSql('ALTER TABLE person DROP version');
        $this->addSql('ALTER TABLE person DROP created_by_id');
        $this->addSql('ALTER TABLE person DROP updated_by_id');
        $this->addSql('ALTER TABLE transmission DROP CONSTRAINT FK_7F87199FB03A8386');
        $this->addSql('ALTER TABLE transmission DROP CONSTRAINT FK_7F87199F896DBBDE');
        $this->addSql('DROP INDEX IDX_7F87199FB03A8386');
        $this->addSql('DROP INDEX IDX_7F87199F896DBBDE');
        $this->addSql('ALTER TABLE transmission DROP created_at');
        $this->addSql('ALTER TABLE transmission DROP updated_at');
        $this->addSql('ALTER TABLE transmission DROP version');
        $this->addSql('ALTER TABLE transmission DROP created_by_id');
        $this->addSql('ALTER TABLE transmission DROP updated_by_id');
    }
}
