<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Bibliographie (phase 2) : recueils, éditions et références structurées.
 *
 * `Hadith.reference` reste en place comme citation verbatim ; ce qu'on
 * interroge désormais, c'est `hadith_reference`. La colonne disparaîtra en
 * phase 3, quand la citation descendra au niveau de la riwāya.
 *
 * Migration PostgreSQL : dev et test tournent sur SQLite.
 */
final class Version20260727095451 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recueils, éditions et références structurées';
    }

    private function abortUnlessPostgres(): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration PostgreSQL uniquement. En dev/test la base est SQLite : utiliser `make db-sync`.',
        );
    }

    public function up(Schema $schema): void
    {
        $this->abortUnlessPostgres();

        $this->addSql('CREATE TABLE collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(64) NOT NULL, title VARCHAR(255) NOT NULL, title_key VARCHAR(255) NOT NULL, title_ar VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, compiler_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FC4D6532989D9B62 ON collection (slug)');
        $this->addSql('CREATE INDEX IDX_FC4D6532EBDDA354 ON collection (compiler_id)');
        $this->addSql('CREATE INDEX IDX_FC4D6532B03A8386 ON collection (created_by_id)');
        $this->addSql('CREATE INDEX IDX_FC4D6532896DBBDE ON collection (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_collection_title_key ON collection (title_key)');
        $this->addSql('CREATE TABLE edition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, publisher VARCHAR(255) DEFAULT NULL, year_ah INT DEFAULT NULL, year_ad INT DEFAULT NULL, reference BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, collection_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A891181F514956FD ON edition (collection_id)');
        $this->addSql('CREATE INDEX IDX_A891181FB03A8386 ON edition (created_by_id)');
        $this->addSql('CREATE INDEX IDX_A891181F896DBBDE ON edition (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_edition_label ON edition (collection_id, label)');
        $this->addSql('CREATE TABLE hadith_reference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(32) DEFAULT NULL, is_primary BOOLEAN NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, hadith_id INT NOT NULL, collection_id INT NOT NULL, edition_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8CD55A9C26312492 ON hadith_reference (hadith_id)');
        $this->addSql('CREATE INDEX IDX_8CD55A9C514956FD ON hadith_reference (collection_id)');
        $this->addSql('CREATE INDEX IDX_8CD55A9C74281A5E ON hadith_reference (edition_id)');
        $this->addSql('CREATE INDEX IDX_8CD55A9CB03A8386 ON hadith_reference (created_by_id)');
        $this->addSql('CREATE INDEX IDX_8CD55A9C896DBBDE ON hadith_reference (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_hadith_reference ON hadith_reference (hadith_id, collection_id, number)');
        $this->addSql('ALTER TABLE collection ADD CONSTRAINT FK_FC4D6532EBDDA354 FOREIGN KEY (compiler_id) REFERENCES person (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE collection ADD CONSTRAINT FK_FC4D6532B03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE collection ADD CONSTRAINT FK_FC4D6532896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT FK_A891181F514956FD FOREIGN KEY (collection_id) REFERENCES collection (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT FK_A891181FB03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT FK_A891181F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hadith_reference ADD CONSTRAINT FK_8CD55A9C26312492 FOREIGN KEY (hadith_id) REFERENCES hadith (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hadith_reference ADD CONSTRAINT FK_8CD55A9C514956FD FOREIGN KEY (collection_id) REFERENCES collection (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hadith_reference ADD CONSTRAINT FK_8CD55A9C74281A5E FOREIGN KEY (edition_id) REFERENCES edition (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hadith_reference ADD CONSTRAINT FK_8CD55A9CB03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hadith_reference ADD CONSTRAINT FK_8CD55A9C896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->abortUnlessPostgres();

        $this->addSql('ALTER TABLE collection DROP CONSTRAINT FK_FC4D6532EBDDA354');
        $this->addSql('ALTER TABLE collection DROP CONSTRAINT FK_FC4D6532B03A8386');
        $this->addSql('ALTER TABLE collection DROP CONSTRAINT FK_FC4D6532896DBBDE');
        $this->addSql('ALTER TABLE edition DROP CONSTRAINT FK_A891181F514956FD');
        $this->addSql('ALTER TABLE edition DROP CONSTRAINT FK_A891181FB03A8386');
        $this->addSql('ALTER TABLE edition DROP CONSTRAINT FK_A891181F896DBBDE');
        $this->addSql('ALTER TABLE hadith_reference DROP CONSTRAINT FK_8CD55A9C26312492');
        $this->addSql('ALTER TABLE hadith_reference DROP CONSTRAINT FK_8CD55A9C514956FD');
        $this->addSql('ALTER TABLE hadith_reference DROP CONSTRAINT FK_8CD55A9C74281A5E');
        $this->addSql('ALTER TABLE hadith_reference DROP CONSTRAINT FK_8CD55A9CB03A8386');
        $this->addSql('ALTER TABLE hadith_reference DROP CONSTRAINT FK_8CD55A9C896DBBDE');
        $this->addSql('DROP TABLE collection');
        $this->addSql('DROP TABLE edition');
        $this->addSql('DROP TABLE hadith_reference');
    }
}
