<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Identité des transmetteurs (phase 1) : formes de noms multiples, dates en
 * fourchettes, tadlīs, et journal des fusions.
 *
 * Migration PostgreSQL : dev et test tournent sur SQLite.
 */
final class Version20260726204148 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Formes de noms, dates en fourchettes et journal des fusions';
    }

    private function abortUnlessPostgres(): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration PostgreSQL uniquement. En dev/test la base est SQLite : utiliser `make db-sync`.',
        );
    }

    public function up(Schema $schema): void
    {
        $this->abortUnlessPostgres();

        $this->addSql('CREATE TABLE person_merge_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, absorbed_slug VARCHAR(64) NOT NULL, absorbed_label VARCHAR(255) NOT NULL, transferred_names JSON NOT NULL, impact JSON NOT NULL, merged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, kept_id INT DEFAULT NULL, merged_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B7C397D6C86B92AE ON person_merge_log (kept_id)');
        $this->addSql('CREATE INDEX IDX_B7C397D650FA8329 ON person_merge_log (merged_by_id)');
        $this->addSql('CREATE TABLE person_name (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, form VARCHAR(255) NOT NULL, form_normalised VARCHAR(255) NOT NULL, script VARCHAR(16) NOT NULL, kind VARCHAR(16) NOT NULL, display BOOLEAN NOT NULL, source VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, person_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D4C5FA2D217BBB47 ON person_name (person_id)');
        $this->addSql('CREATE INDEX IDX_D4C5FA2DB03A8386 ON person_name (created_by_id)');
        $this->addSql('CREATE INDEX IDX_D4C5FA2D896DBBDE ON person_name (updated_by_id)');
        $this->addSql('CREATE INDEX idx_person_name_normalised ON person_name (form_normalised)');
        $this->addSql('CREATE UNIQUE INDEX uniq_person_name_form ON person_name (person_id, form, script)');
        $this->addSql('ALTER TABLE person_merge_log ADD CONSTRAINT FK_B7C397D6C86B92AE FOREIGN KEY (kept_id) REFERENCES person (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person_merge_log ADD CONSTRAINT FK_B7C397D650FA8329 FOREIGN KEY (merged_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person_name ADD CONSTRAINT FK_D4C5FA2D217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person_name ADD CONSTRAINT FK_D4C5FA2DB03A8386 FOREIGN KEY (created_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person_name ADD CONSTRAINT FK_D4C5FA2D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES curator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person ADD birth_ah_min INT DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD birth_ah_max INT DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD death_ah_min INT DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD death_ah_max INT DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD mudallis BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE person ADD tadlis_type VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD tadlis_rank INT DEFAULT NULL');
        $this->addSql('ALTER TABLE person DROP name');
        $this->addSql('ALTER TABLE person DROP name_ar');
    }

    public function down(Schema $schema): void
    {
        $this->abortUnlessPostgres();

        $this->addSql('ALTER TABLE person_merge_log DROP CONSTRAINT FK_B7C397D6C86B92AE');
        $this->addSql('ALTER TABLE person_merge_log DROP CONSTRAINT FK_B7C397D650FA8329');
        $this->addSql('ALTER TABLE person_name DROP CONSTRAINT FK_D4C5FA2D217BBB47');
        $this->addSql('ALTER TABLE person_name DROP CONSTRAINT FK_D4C5FA2DB03A8386');
        $this->addSql('ALTER TABLE person_name DROP CONSTRAINT FK_D4C5FA2D896DBBDE');
        $this->addSql('DROP TABLE person_merge_log');
        $this->addSql('DROP TABLE person_name');
        $this->addSql('ALTER TABLE person ADD name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE person ADD name_ar VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE person DROP birth_ah_min');
        $this->addSql('ALTER TABLE person DROP birth_ah_max');
        $this->addSql('ALTER TABLE person DROP death_ah_min');
        $this->addSql('ALTER TABLE person DROP death_ah_max');
        $this->addSql('ALTER TABLE person DROP mudallis');
        $this->addSql('ALTER TABLE person DROP tadlis_type');
        $this->addSql('ALTER TABLE person DROP tadlis_rank');
    }
}
